### ISSUE TITLE
Not working on Zenfone 2

### ISSUE THREAD

**Issue by kaaninel** [Aricwithana/DOMLauncher2#5]
Isn't it support x86 ? i downloaded from play store but it crashes. I was thinking writing a launcher with meteor framework then i saw this and it could make so many things easier if it works on x86.

**Comment by Aricwithana** [comment]
There is no current x86 support for DOMLauncher.  With the code fully available the plugins, manifest and main java file could be brought over.  

I'll look into supporting x86 for future versions.
